### PR TITLE
Feature- branch. Complete project pull request

### PR DESCRIPTION
**Pull request by canriquez**
Please review this project.
This request includes:

- Full Newsweek clone markup and CSS.
- Complete responsiveness tested to the extent of my current capabilities
- Specifications fulfilled as per original Microverse / The Odin project requirements.

Thanks

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Carlos!  
### Your project looks :+1: amazing! You created amazing Newsweek clone and Readme file is beautifully descriptive!
Here few things to change before this project can be approved:
* [ ] This part of original website is missing:
image
* [ ] It seems, that horizontal scrollbar appears in tablet and mobile versions of this project.
* Tablet version:
image
* Mobile version:
image
* [ ] Inline styling should be removed. Some links in your project have `<style>` inside, please move styling to css file.
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by canriquez** [comment]
all recommended changes executed: Missing section, Overflow issues on mobile/tablet and inline styling back to CSS . 
Thanks Olga 🙏

**Comment by rOluochKe** [comment]
@canriquez good job for the work done.
- I see you have made all the changes from the previous review.
- Make this one change, merge to master and submit your project as completed. Make the search field better
search
- I approve of this project. Good luck with the next one.

**Pull request merged**
